import sanjhi from "/sanjhi.jpg"
import jamdani from "/jamdani.jpg"
import suit from "/suit.jpg"
import kids1 from "/kids1.jpeg"
import kids2 from "/kids2.jpg"
import kids3 from "/kids3.jpg"
import kids4 from "/kids4.jpg"
import kids5 from "/kids5.jpg"
export const all_products=[
         {id:1,
                  name:"striped overlap hem blouse",
                  category:"womens",
                  image:"https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNhcmVlfGVufDB8fDB8fHww",
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:2,
                  name:"sanjhi arts",
                  category:"womens",
                  image:sanjhi,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:3,
                  name:"jamdani Bengali saree",
                  category:"womens",
                  image:jamdani,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:4,
                  name:"jamdani Bengali saree",
                  category:"womens",
                  image:jamdani,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:5,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:6,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:7,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:8,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:9,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:10,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:11,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:12,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:13,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:14,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:15,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:16,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:17,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:18,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:19,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:20,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:21,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:22,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:23,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:24,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:25,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:26,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:27,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:28,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:29,
                  name:"Bandhgala suit",
                  category:"mens",
                  image:suit,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:30,
                  name:"boys checked shirts",
                  category:"kids",
                  image:kids1,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:31,
                  name:"infant wear",
                  category:"kids",
                  image:kids2,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:32,
                  name:"Bandhgala suit",
                  category:"kids",
                  image:kids3,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:33,
                  name:"kids girls jacket",
                  category:"kids",
                  image:kids4,
                  new_price:60.0,
                  old_price:110.5
                  },
         {id:34,
                  name:"girls denim",
                  category:"kids",
                  image:kids5,
                  new_price:60.0,
                  old_price:110.5
                  },
]